# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi!
tagline:          "Blog Photonom"
description:      'I am Kerem, and I am a junior CS student.'
url:              https://photonom.github.io/
baseurl:          ''

paginate:         5

# Custom vars
version:          2.1.0
plugins: [jekyll-paginate]
