# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Hi!
tagline:          "Blog Photonom"
description:      'We are The Senior Factory and this is Photonom'
url:              https://photonom.github.io/
baseurl:          ''

paginate:         5

# Custom vars
version:          2.1.0
plugins: [jekyll-paginate]
